### PR TITLE
Refactor Social Login

### PR DESCRIPTION
**Pull request by rajbdilip**
- Created a base `SocialMedia` class that can be extended to add a new Social Media easily. `SocialMedia` class defines common methods and declares the ones that Social Media needs to define
- Other related changes

### CODE REVIEW

**Comment by xurizaemon** [comment]
Hey Raj. This looks good thanks. I have a couple of questions on it.

1. [Social Media](https://en.wikipedia.org/wiki/Social_media) is not the same as authentication. The base class here deals almost exclusively with authenticating against a remote auth provider. I would recommend renaming that base class to be more accurately descriptive of what it actually does.

2. I see this base class implements an http method - that feels out of place here. Would using something like [Symfony\HttpFoundation\Request](http://api.symfony.com/3.1/Symfony/Component/HttpFoundation/Request.html) be better? (CiviCRM is already using this [in a couple of places](https://github.com/civicrm/civicrm-core/search?utf8=%E2%9C%93&q=httpfoundation).

**Comment by rajbdilip** [comment]
@xurizaemon How about `OAuthProvider` or something in that line? Do you have any suggestions?

**Comment by xurizaemon** [comment]
That sounds a lot more like what it actually does, yes - provided the
networks are all using *OAuth* - otherwise maybe AuthProvider?

**Comment by rajbdilip** [comment]
@xurizaemon So, `OAuthProvider` or `AuthProvider`? I like `OAuthProvider` more. Since all the newtorks will provide Open Authentication.

**Pull request merged**
